### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by TolikCorp** [GAMMACASE/FastdlUpdater#3]
To expand the possibilities, I suggest
1. Adding keys that will allow you to output or not output information about files.
  -c, --changes          like verbose but report only when a change is made (if no changes - log output clean)
  -v, --verbose          output a diagnostic for every file processed
2.
-R, --recursive        check files and directories recursively
![image](https://user-images.githubusercontent.com/6604099/225227256-f6231ce2-97fe-4cf6-b464-d01ec7bda921.png)

3. In the exception list, specify the relative path with the directory. For example,
maps/ar_bagage.bsp

**Comment by GAMMACASE** [comment]
Have a few questions:
1. ``-c`` here is already a current behavior of the script, isn't it?
2. It's by default recursive as of now;
3. When you say ``exception list`` do you mean blacklist file? If so, could you provide your use case where filename is not enough?

**Comment by TolikCorp** [comment]
> * `-c` here is already a current behavior of the script, isn't it?
isn't it
![image](https://user-images.githubusercontent.com/6604099/225230631-ac600aa5-a29a-4d97-91b7-78f4b584f5d9.png)
![image](https://user-images.githubusercontent.com/6604099/225231144-adaaf5c6-11b1-4fa9-a154-9bbe0cd92f26.png)

> * It's by default recursive as of now;
yes, I initially did not notice that there are no necessary file formats in the folder with maps
its ok
![image](https://user-images.githubusercontent.com/6604099/225232005-38a2451c-d2b3-4914-b84f-9809b7d4dd29.png)

> 3\. When you say `exception list` do you mean blacklist file? If so, could you provide your use case where filename is not enough?
`exception list` = blacklist file
this will reduce the error of incorrectly determining the location of the excluded file

**Comment by GAMMACASE** [comment]
So, to continue with the discussion:
1 - Can you elaborate on your use case here? I could agree on some filtering of blacklist notifications, but not sure about the general messages at start and end of the output and why you would want to have that stripped;
3 - Also would like to hear your use case here, as I don't really imagine a situation where multiple files with the same name + extension would be present in multiple folders (and that is the format you use in the blacklist), altho that's not something that's hard to implement, just don't want to overcomplicate a system if there are no particular use case for it.

**Comment by TolikCorp** [comment]
> 1 - Can you elaborate on your use case here? I could agree on some filtering of blacklist notifications, but not sure about the general messages at start and end of the output and why you would want to have that stripped;

I use commands every 5 minutes and write the results to a log file.
Executable commands:

# tf2_1
*/5 * * * * su - root -c 'chown -R -c gs-1:gs-1 /home/gs-1/gameservers/tf2_1' >> /home/gs-1/gameservers/logs/tf2_1_chown_`date '+\%Y.\%m.\%d'`.log 2>&1
*/5 * * * * su - root -c 'chmod -R -c 775 /home/gs-1/gameservers/tf2_1' >> /home/gs-1/gameservers/logs/tf2_1_chmod_`date '+\%Y.\%m.\%d'`.log 2>&1
*/5 * * * *  su - gs-1 -c 'cd /home/gs-1/gameservers/tf2_1/fastdl && python3 ./fastdl.py' >> /home/gs-1/gameservers/logs/tf2_1_fastdl_`date '+\%Y.\%m.\%d'`.log 2>&1

When I open the log files, only the result of the work is visible for the chmod & chown command. And in fastdl - spam.

![image](https://user-images.githubusercontent.com/6604099/225495182-d5314dce-fd03-4454-9518-93b66ca45fa3.png)




> 3 - Also would like to hear your use case here, as I don't really imagine a situation where multiple files with the same name + extension would be present in multiple folders (and that is the format you use in the blacklist), altho that's not something that's hard to implement, just don't want to overcomplicate a system if there are no particular use case for it.

for the universality of the solution, we can leave it like this, it works the same

**Comment by GAMMACASE** [comment]
Alright, added the verbosity level argument (you can see what levels are available via ``python3 ./fastld.py -h`` now). For your use case ``-v0`` argument would provide what you asked for. Lmk if there's anything else needs to be addressed.
