### ISSUE TITLE
Implicit behavior argument "-v 0"

### ISSUE THREAD

**Issue by TolikCorp** [GAMMACASE/FastdlUpdater#4]
Hello, I found an implicit behavior.
Argument -v 0
I use only third-party sounds, and the maps are standard (they are all in the exclusion list).
In the logs I see the creation and deletion of a folder.

Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...
Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...
Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...
Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...
Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...
Directory ../public_html/fastdl/maps wasn't found on fastdl path, creating...
Found empty directory ../public_html/fastdl/maps on fastdl, removing...

**Comment by GAMMACASE** [comment]
Should be fine now, redownload the script from the master.
